[workspace]
resolver = "2"
members = ["crates/next-swc-tagging"]

[workspace.dependencies]
swc_core = "0.104.2"

[profile.release]
# This removes more dead code
codegen-units = 1
lto = false
# Optimize for size
opt-level = "s"
# Strip debug symbols
strip = "symbols"
