[package]
name = "next_swc_tagging"
authors = ["Mathis Møller"]
description = "SWC plugin for automatic jotai atom debug labels"
license = "MIT"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0.160"
serde_json = "1.0.96"
swc_core = { workspace = true, features = [
  "common",
  "ecma_ast",
  "ecma_parser",
  "ecma_utils",
  "ecma_visit",
  "ecma_plugin_transform",
] }

[dev-dependencies]
swc_core = { workspace = true, features = [
  "ecma_plugin_transform",
  "ecma_transforms_react",
  "testing_transform",
] }
testing = "0.33.6"
